objectList = {
  toothBrush =       {name = "Toothbrush",        length = 13, volume = 52, rarity = 1, pickupSound = nil, previewData = {18,7}},
  thumbTack =        {name = "Thumb Tack",        length = 4, volume = 10, rarity = 1, pickupSound = nil, previewData = {14,13}},
  eraser =           {name = "Eraser",            length = 6, volume = 72, rarity = 1, pickupSound = nil, previewData = {12,10}},
  leaf =             {name = "Leaf",              length = 8, volume = 2, rarity = 1, pickupSound = nil, previewData = {21,13}},
  jellyBeanBlue =    {name = "Blue Jellybean",    length = 1, volume = 1, rarity = 1, pickupSound = nil, previewData = {12,25}},
  jellyBeanRed =     {name = "Red Jellybean",     length = 1, volume = 1, rarity = 1, pickupSound = nil, previewData = {12,25}},
  jellyBeanYellow =  {name = "Yellow Jellybean",  length = 1, volume = 1, rarity = 1, pickupSound = nil, previewData = {12,25}},
  jellyBeanGreen =   {name = "Green Jellybean",   length = 1, volume = 1, rarity = 1, pickupSound = nil, previewData = {12,25}},
  jellyBeanWhite =   {name = "White Jellybean",   length = 1, volume = 1, rarity = 1, pickupSound = nil, previewData = {12,25}},
  jellyBeanGray =    {name = "Gray Jellybean",    length = 1, volume = 1, rarity = 1, pickupSound = nil, previewData = {12,25}},
  ant =              {name = "Ant",               length = 5, volume = 6, rarity = 1, pickupSound = nil, previewData = {10,15}},
  pencil =           {name = "Pencil",            length = 15, volume = 14, rarity = 1, pickupSound = nil, previewData = {18,7}},
  paper =            {name = "Paper",             length = 15, volume = 5, rarity = 1, pickupSound = nil, previewData = {19,5}},
  mug =              {name = "Mug",               length = 5, volume = 66, rarity = 1, pickupSound = nil, previewData = {5,8}},
  glass =            {name = "Glass",             length = 8, volume = 54, rarity = 1, pickupSound = nil, previewData = {0,6}},
  playingCard =      {name = "Playing Card",      length = 8, volume = 2, rarity = 1, pickupSound = nil, previewData = {20,12}},
  ruler =            {name = "Ruler",             length = 16, volume = 24, rarity = 1, pickupSound = nil, previewData = {19,6}},
  appleGreen =       {name = "Green Apple",       length = 5, volume = 64, rarity = 1, pickupSound = nil, previewData = {3,8}},
  appleRed =         {name = "Red Apple",         length = 5, volume = 64, rarity = 1, pickupSound = nil, previewData = {3,8}},
  toothpaste =       {name = "Toothpaste",        length = 12, volume = 62, rarity = 1, pickupSound = nil, previewData = {15,7}},
  bucket =           {name = "Bucket",            length = 15, volume = 900, rarity = 1, pickupSound = nil, previewData = {2,3}},
  stopSign =         {name = "Stop Sign",         length = 61, volume = 296, rarity = 1, pickupSound = nil, previewData = {-12,1.6}},
  lethalHorn =       {name = "Horn",              length = 11, volume = 100, rarity = 1, pickupSound = nil, previewData = {12,6}},
  soap =             {name = "Soap",              length = 6, volume = 48, rarity = 1, pickupSound = nil, previewData = {13,10}},
  cupcake =          {name = "Cupcake",           length = 5, volume = 125, rarity = 1, pickupSound = nil, previewData = {4,8}},
  chocolate =        {name = "Chocolate",         length = 13, volume = 91, rarity = 1, pickupSound = nil, previewData = {18,6}},
  pizza =            {name = "Pizza",             length = 9, volume = 27, rarity = 1, pickupSound = nil, previewData = {20,9}},
  lollipop =         {name = "Lollipop",          length = 7, volume = 10, rarity = 1, pickupSound = nil, previewData = {18,11}},
  cookie =           {name = "Cookie",            length = 10, volume = 41, rarity = 1, pickupSound = nil, previewData = {18,8}},
  icecream =         {name = "Icecream",          length = 9, volume = 54, rarity = 1, pickupSound = nil, previewData = {12,8}},
  bookBlue =         {name = "Book",              length = 15, volume = 425, rarity = 1, pickupSound = nil, previewData = {16,5}},
  carrot =           {name = "Carrot",            length = 7, volume = 21, rarity = 1, pickupSound = nil, previewData = {10,9}},
  glasses =          {name = "Glasses",           length = 12, volume = 8, rarity = 1, pickupSound = nil, previewData = {15,6}},
  sunflower =        {name = "Sunflower",         length = 35, volume = 131, rarity = 1, pickupSound = nil, previewData = {-12,2.2}},
  cricket =          {name = "Cricket",           length = 4, volume = 16, rarity = 1, pickupSound = nil, previewData = {5,10}},
  smallEnemySpider = {name = "Small Enemy Spider",length = 6, volume = 74, rarity = 1, pickupSound = nil, previewData = {8,7}},
  ladybug =          {name = "Ladybug",           length = 3, volume = 11, rarity = 1, pickupSound = nil, previewData = {10,15}},
  fly =              {name = "Fly",               length = 5, volume = 20, rarity = 1, pickupSound = nil, previewData = {10,11}},
  caterpillar =      {name = "Caterpillar",       length = 8, volume = 9, rarity = 1, pickupSound = nil, previewData = {10,10}},
  dragonFly =        {name = "Dragonfly",         length = 8, volume = 12, rarity = 1, pickupSound = nil, previewData = {12,8}},
  worm =             {name = "Worm",              length = 8, volume = 8, rarity = 1, pickupSound = nil, previewData = {18,10}},
  maggot =           {name = "Maggot",            length = 3, volume = 3, rarity = 1, pickupSound = nil, previewData = {15,15}},
  spider =           {name = "Spider",            length = 4, volume = 8, rarity = 1, pickupSound = nil, previewData = {15,13}},
  snail =            {name = "Snail",             length = 4, volume = 8, rarity = 1, pickupSound = nil, previewData = {6,15}},
  slug =             {name = "Slug",              length = 4, volume = 4, rarity = 1, pickupSound = nil, previewData = {10,17}},
}